version: "3"

services:
  my-dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-dbt:latest
    container_name: dbt_container
    environment:
      - ORA_PYTHON_DRIVER_TYPE=thin
      - WALLET_LOCATION=/usr/.config
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - TNS_ADMIN=/usr/.config
      - DBT_ORACLE_USER=${DBT_ORACLE_USER}
      - DBT_ORACLE_PASSWORD=${DBT_ORACLE_PASSWORD}
      - DBT_ORACLE_SCHEMA=${DBT_ORACLE_SCHEMA}
      - DBT_ORACLE_HOST=${DBT_ORACLE_HOST}
      - DBT_ORACLE_SERVICE=${DBT_ORACLE_SERVICE}
      - DBT_ORACLE_DATABASE=${DBT_ORACLE_DATABASE}
      - DBT_ORACLE_TNS_NAME=${DBT_ORACLE_TNS_NAME}
    network_mode: host
    volumes:
      - ./app:/usr/app
      - ./.config:/usr/.config
    ports:
      - 8081:8080
